### ISSUE TITLE
Support vim with python3

### ISSUE THREAD

**Issue by curist** [larrylv/ycm-elixir#1]
Some `vim` comes with only `python3` integration,
so here is the idea to support both `python2` and `python3`.

``` vim
let s:version = ''
if has('python3')
  let s:version = '3'
endif

exec 'py'.s:version.' import ycmelixir'

exec 'py'.s:version.' ycmelixir.hijack_global_ycm_extra_conf()'
exec 'py'.s:version.' ycmelixir.hijack_ycmd_identifiers_regex()'
```

Feel free to change anything.

**Comment by larrylv** [comment]
@curist Could you help to prepare a PR so that I could merge it please? Thank you.
