### ISSUE TITLE
It doesn't help

### ISSUE THREAD

**Issue by kana-sama** [larrylv/ycm-elixir#3]
After entering `.`:
![_2017-02-09_18-36-42](https://cloud.githubusercontent.com/assets/7101648/22790330/dd130eb0-eef6-11e6-8247-d669fe07e855.png)

After `ctrl+space`:
![_2017-02-09_18-36-57](https://cloud.githubusercontent.com/assets/7101648/22790329/dd0e4736-eef6-11e6-8541-da1ae8ff78d6.png)

YCM and alchemist were installed

**Comment by larrylv** [comment]
@kana-sama Have you tried this in a mix project?

**Comment by waiting-for-dev** [comment]
Same for me, it only display alchemist autocompletions if I press `<C-x>< C-o>`. Before that it is plain YCM.

Please, tell me if you need any debugging information.

Thanks

**Comment by larrylv** [comment]
@waiting-for-dev I think with current `alchemist.vim`, there is no need for this plugin. I disabled my `ycm-elixir`, and the completion stills works fine for me.

<img width="435" alt="screen shot 2017-08-02 at 10 36 31" src="https://user-images.githubusercontent.com/531650/28886694-3924c166-776f-11e7-8db7-0fe5dd8236ea.png">

**Comment by larrylv** [comment]
I will update my README. :)

**Comment by waiting-for-dev** [comment]
Hmm, fine, but it still is not working for me :)
